Models/LoginView.cs
using System.ComponentModel.DataAnnotations;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InmobiliariaAlvarezM.Models
{
    public class LoginView
    {
        //[Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
       // [Required]
        [DataType(DataType.Password)]
        public string Clave { get; set; }
    }
}

Controllers/PagoController.cs
using InmobiliariaAlvarezM.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InmobiliariaAlvarezM.Controllers
{
    public class PagoController : Controller
    {
        private readonly IConfiguration configuration;
        //private readonly IWebHostEnvironment environment;
        private readonly IRepositorioPago repositorio;
        private readonly IRepositorioContrato repositorioContrato;
        private readonly IRepositorioInmueble repositorioInmueble;
        private readonly IRepositorioInquilino repositorioInquilino;
        public PagoController(IConfiguration configuration, IRepositorioPago repositorio, IRepositorioContrato repositorioContrato, IRepositorioInmueble repositorioInmueble, IRepositorioInquilino repositorioInquilino)
        {
            this.configuration = configuration;
            //this.environment = environment;
            this.repositorio = repositorio;
            this.repositorioContrato = repositorioContrato;
            this.repositorioInmueble = repositorioInmueble;
            this.repositorioInquilino = repositorioInquilino;
        }

        // GET: PagoController
        
        public ActionResult Index()
        {
            var lista = repositorio.ObtenerTodos();
            return View(lista);
        }
      
        // GET: PagoController/Details/5
        public ActionResult Details(int id)
        {
            var p = repositorio.ObtenerPorId(id);
            return View(p);
        }

        [Authorize(Policy = "Administrador")]
        public ActionResult Create(int id)  
            {
                ViewBag.Contrato = repositorioContrato.ObtenerTodos();
                return View();
            }

        [Authorize(Policy = "Administrador")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int id, Pago pago)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    repositorio.Alta(pago);
                    var lista = repositorio.ObtenerTodos();
                    return View("Index", lista);
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return RedirectToAction(nameof(Index));
            }
        }


        // GET: PagoController/Edit/5
        public ActionResult Edit(int id)
        {

            var entidad = repositorio.ObtenerPorId(id);
            ViewBag.Inquilino = repositorioInquilino.ObtenerTodos();
            ViewBag.Inmueble = repositorioInmueble.ObtenerTodos();
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            if (TempData.ContainsKey("Error"))
                ViewBag.Error = TempData["Error"];
            return View(entidad);
        }

        // POST: PagoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Pago entidad)
        {
            try
            {
                entidad.IdPago = id;
                repositorio.Modificacion(entidad);
                TempData["Mensaje"] = "Datos guardados correctamente";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View();
            }
        }

        // GET: PagoController/Delete/5
        [Authorize(Policy = "Administrador")]
        public ActionResult Delete(int id)
        {
            var entidad = repositorio.ObtenerPorId(id);
            ViewBag.Inquilino = repositorioInquilino.ObtenerTodos();
            ViewBag.Inmueble = repositorioInmueble.ObtenerTodos();
            TempData["IdContrato"] = entidad.IdContrato;
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            if (TempData.ContainsKey("Error"))
                ViewBag.Error = TempData["Error"];
            return View(entidad);
        }


        // POST: PagoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Administrador")]
        public ActionResult Delete(int id, Pago entidad)
        {
            try
            {
                entidad.IdPago = id;
                repositorio.Baja(id);
                TempData["Mensaje"] = "Eliminacion realizada correctamente";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View();
            }
        }
        public ActionResult PorContrato(int id)
        {
            var lista = repositorio.BuscarPorContrato(id);
            if (TempData.ContainsKey("Id"))
                ViewBag.Id = TempData["Id"];
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            ViewBag.Contrato = repositorioContrato.ObtenerPorId(id);
            return View(lista);
        }

    }

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inmobiliaria AlvarezM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InmobiliariaAlvarezM</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item mr-2">
                                <div class="dropdown">
                                    <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Administrar
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="Propietario" asp-action="Index"><i class="bi bi-file-person-fill">    </i>Propietarios</a>
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="Inmueble" asp-action="Index"><i class="bi bi-house-fill">    </i>Inmuebles</a>
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="Inquilino" asp-action="Index"><i class="bi bi-file-person">    </i>Inquilinos</a>
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="Contrato" asp-action="Index"><i class="bi bi-calendar4-range">   </i>Contratos</a>
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="Pago" asp-action="Index"><i class="bi bi-credit-card-fill">   </i>Pagos</a>
                                        @if (User.IsInRole("SuperAdministrador"))
                                        {
                                            <a class="dropdown-item text-dark" asp-area="" asp-controller="Usuario" asp-action="Index"><i class="bi bi-people-fill">   </i>Usuarios</a>
                                        }
                                    </div>
                                </div>
                            </li>
                            <li class="nav-item mr-2">
                                <div class="dropdown">
                                    <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Informes
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="Pago" asp-action="PorContrato">Pagos por contrato</a>
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="Inmueble" asp-action="MostrarInmueblesPorPropietario">Inmuebles por propietario</a>
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="Inmueble" asp-action="Disponible">Inmuebles Disponibles</a>
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="Inmueble" asp-action="Fechas">Disp. entre Fechas</a>
                                    </div>
                                </div>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav text-right">
                        <li class="nav-item">

                            @if (!User.Identity.IsAuthenticated)
                            {
                                <a class="btn btn-primary" asp-area="" asp-controller="Usuario" asp-action="Login">
                                    Acceder
                                </a>
                            }
                            else
                            {
                                <div class="dropdown">
                                    <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        @User.Identity.Name
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="Usuario" asp-action="Perfil"><i class="bi bi-person">    </i>Perfil</a>
                                        <hr />
                                        <a class="dropdown-item text-danger" asp-area="" asp-controller="Usuario" asp-action="Logout"><i class="bi bi-box-arrow-right">   </i>Salir</a>
                                    </div>
                                </div>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - InmobiliariaAlvarezM - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Login.cshtml
@model InmobiliariaAlvarezM.Models.LoginView

<h4>Inicio de sesión</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Usuario" asp-action="Login">
            <div  asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Clave" class="control-label"></label>
                <input asp-for="Clave" class="form-control" />
                <span asp-validation-for="Clave" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Iniciar sesión" class="btn btn-primary" />
            </div>
            @if (ViewBag.ErrorLogin != null)
            {
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    @ViewBag.ErrorLogin
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true"><span class="lnr lnr-cross-circle"></span></span>
                    </button>
                </div>
            }
        </form>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Shared/_LogoutModal.cshtml
<div class="modal fade" id="logout_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Cierre de sesión</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ¿Seguro que desea cerrar sesión?
            </div>
            <div class="modal-footer">
                <form asp-controller="Usuario" asp-action="Logout">
                    <button type="submit" class="btn btn-danger">Cerrar sesión</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                </form>
            </div>
        </div>
    </div>
</div>